# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjZxr-XGcLIcAxCodpvgzRC1lJfPsS_c
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/mnist_train_small.csv")
display(df.head())

df_test = pd.read_csv("/content/sample_data/mnist_test.csv")
display(df_test.head())



import pandas as pd

df = pd.read_csv("/content/sample_data/mnist_train_small.csv")
display(df.head())

print(df.head(3))
print(df.tail())

print(df.info())

"""CREATE A SIMPLE DATA SET

"""

import pandas as pd
data = {'A':[1,2,3,4,5], 'B':[6,7,8,9,10], 'C':[11,12,13,14,15]}
df = pd.DataFrame(data)
print(df)

"""2.sing Descriptive Statistics using describe()"""

summary_stats = df.describe()
print(summary_stats)

"""3. MEAN MEDIAN AND MODE

"""

mean = df.mean()
median = df.median()
mode = df.mode()
print("Mean:\n", mean)
print("Median:\n", median)
print("Mode:\n", mode)

"""4. Calculate the median, first quartile (Q1), and third quartile (Q3)"""

import numpy as np
data  = np.array([1,2,3,4,5,6,7,8,9,10])

# calculating median(q2)
median = np.quantile(data,0.5)

# calculating first quartile(q1)
q1 = np.quantile(data, 0.25)

# calculating third quartile(q3)
q3 = np.quantile(data, 0.75)

print("Median (Q2):", median)
print("First Quartile (Q1):", q1)
print("Third Quartile (Q3):", q3)